/* Object structure */

// title: '',
// imgSource: '',
// altText: '',
// description: '',
// tools: '',
// focus: [],
// liveLink: '',
// gitHubLink: '',
// detail: ['', '', ''],

const ProjectData = [
  {
    title: 'Weathrly',
    imgSource: 'weathrly',
    altText: 'Desktop and mobile screenshots of mobile app',
    description: 'A weather app built using React, Redux, and Geolocation.',
    tools: 'React, Redux, Firebase, Sass',
    focus: ['Leading project development and testing', 'Implementing Redux', 'Working with challenging data sets'],
    liveLink: 'https://lrknaff.github.io/weather-tracker/#/?_k=lfklre',
    gitHubLink: 'https://github.com/rcwestlake/weather-tracker',
    detail: ['In this app, we use the Geolocation and OpenWeather APIs. The Geolocation is triggered when the user visits the page.', 'The user can add up to three cities to their account and can view updated weather info whenever they come back. In the Settings page, they can delete or add more cities.', 'The most challenging part was parsing the data we got back from OpenWeather. Their API structure was not easy navigate and map through the right info. In addition, this was my first exposure to Redux, so understanding how that works took time.', 'I built it with a small team, where I was in charge of the bulk of the Redux/component work, as well as testing.'],
  },
  {
    title: 'Github Notetaker',
    imgSource: 'githubNotetaker',
    altText: '4 screenshots of phone with Github Notetaker app',
    description: 'React Native app that uses the Github API',
    tools: 'React Native, Firebase',
    focus: ['Learn React Native', 'Simple and clean design'],
    gitHubLink: 'https://github.com/rcwestlake/github-notetaker',
    detail: ['This was a side-project. The app pull from the Github API based on a username, then allows the user to see that person\'s profile and repos. Once a repo is clicked on, it takes them to the WebView.', 'This was my first project in React Native, so the most challenging part was understanding how to route and pass state/props.'],
  },
  {
    title: 'chatterbox',
    imgSource: 'chatterbox',
    altText: 'Screenshot on laptop and mobile of chatterbox app',
    description: 'Realtime chat app built with React and Firebase',
    tools: 'React, Firebase, Enzyme (testing), Webpack',
    focus: ['Working with backend', 'Authentication', 'Test driven development'],
    liveLink: 'https://chatterbox-9c7e1.firebaseapp.com/',
    gitHubLink: 'https://github.com/rcwestlake/chatterbox',
    detail: ['This project was focused on authentication and building a realtime app with multiple users. We used Firebase to store data as well as help with Google auth. Once logged in, a user can see who else in the messaging app and read past messages. They can also sort messages from oldest to newest as well as filter by user.', 'I worked with one other person, and at the beginning of the project, decided we wanted to take an agile, test-driven approach. While not perfect, it was a great experience.', 'The most challenging part was integrating auth with Firebase and managing a larger user base.'],
  },
  {
    title: 'FareHarbor ToolKit',
    imgSource: 'fareharbor',
    altText: 'Screenshot of FareHarbor project on laptop device',
    description: 'Real-world feature-set built for a startup in the online travel services industry',
    tools: 'Javascript, Node/Express',
    focus: ['JavaScript module pattern', 'Integrating with a large, established code base', 'Building scale for a real-world app', 'Clear documentation for future use'],
    liveLink: 'http://www.fareharbor.com',
    gitHubLink: 'https://github.com/rcwestlake/fare-harbor-toolkit',
    detail: ['This is a project built for FareHarbor, an online travel services company. Their primary product allows tour and activity companies to provide a booking and ticketing service online. My project was to build the platform to create and customize new tools they can easily embed in client sites. While they have a well-run backend system they didn\'t have a integrated frontend for tools.', 'When given the project, it was clear scalability and flexibility were key. They needed to be able to completely and easily customize the tools and then simply add one script to the site. Our hope is that they will increase conversions for FareHarbor and their clients.', 'It was built in JavaScript and Node (Express). Testing was done with Selenium Webdriver. In order to be compatible with all browsers and not have dependencies it was built in vanillaJS (not fancy ES6 stuff).'],
  },
  {
    title: 'PennyWise',
    imgSource: 'pennyWise',
    altText: '4 screenshots of phone with PennyWise app',
    description: 'MVP budget app built with React Native',
    tools: 'React Native, Firebase, XCode',
    focus: ['Building mobile first', 'Two week agile cycle', 'Pitching and leading project'],
    gitHubLink: 'https://github.com/rcwestlake/BudgetApp',
    detail: ['This was a two week project in React. I thought it would be fun and challenging to build a mobile app with React Native, pitched the idea to instructors, and led the group throughout the two week timeframe. Given it was a new technology, we were only able to build an MVP, but the main functionality is there.', 'From the outset, our group (me and two others) decided to focus on quality over quantity, so made it a monthly-focused budget. Our goal was to build something that a new budgeter could easily pick up, use, and enjoy.', 'We use Sketch for wireframing the app and Firebase for the backend.'],
  },
  {
    title: '2048',
    imgSource: '2048',
    altText: 'Screenshot of 2048 project on laptop and mobile device',
    description: 'Clone of the popular 2048 game',
    tools: 'Javascript, jQuery, Mocha/Chai (testing)',
    focus: ['Prototypal inheritance', 'Test Driven Development', 'Logic'],
    liveLink: 'https://rcwestlake.github.io/2048/',
    gitHubLink: 'https://github.com/rcwestlake/2048',
  },
  {
    title: '2DoBox',
    imgSource: '2DoBox',
    altText: 'Screenshot of 2DoBox project on laptop and mobile device',
    description: 'Simple 2Do app - users can filter, sort, and see completed tasks',
    tools: 'JavaScript, jQuery, Sass, Webpack',
    focus: ['Localstorage', 'JavaScript'],
    liveLink: 'https://mziccardi.github.io/2DoBox-Pivot/',
    gitHubLink: 'https://github.com/rcwestlake/2DoBox-Pivot',
    detail: ['2DoBox was built with Javascript, jQuery, Sass, and Webpack. Our feature testing was done using webdriver.io and Selenium, unit tests were done using Mocha and Chai.'],
  },
]

export default ProjectData
